apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sl-data
  namespace: sessionledger
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
